
var systemMonitor;
var cityControl;
var userName;
var mobileNumber;
var emailId;
var courseName;
var trainerName;
var collegeName;
var department;
var subject;
var section;
var marks;
var grade;
var attendance;
var projectName;
var companyName;
var salary;
var address;
var countryName;
var stateName;


console.log(systemMonitor);
console.log(cityControl);
console.log(userName);
console.log(mobileNumber);
console.log(emailId);
console.log(courseName);
console.log(trainerName);
console.log(collegeName);
console.log(department);
console.log(subject);
console.log(section);
console.log(marks);
console.log(grade);
console.log(attendance);
console.log(projectName);
console.log(companyName);
console.log(salary);
console.log(address);
console.log(countryName);

let student1 = "A";
let student2 = "B";
let student3 = "C";
let student4 = "D";
let student5 = "E";
let student6 = "F";
let student7 = "G";
let student8 = "H";
let student9 = "I";
let student10 = "J";
let student11 = "K";
let student12 = "L";
let student13 = "M";
let student14 = "N";
let student15 = "O";
let student16 = "P";
let student17 = "Q";
let student18 = "R";
let student19 = "S";
let student20 = "T";
let student21 = "U";
let student22 = "V";
let student23 = "W";
let student24 = "X";
let student25 = "Y";
let student26 = "Z";
let student27 = "AA";
let student28 = "BB";
let student29 = "CC";
let student30 = "DD";


const pi = 3.14;
const days = 7;
const months = 12;
const year = 2026;
const countryCode = "+91";
const appName = "FoodApp";
const version = "1.0";
const maxUsers = 1000;
const minAge = 18;
const maxAge = 60;
const tax = 18;
const discount = 10;
const speedLimit = 80;
const passMark = 35;
const fullMark = 100;
const admin = "Admin";
const language = "JavaScript";
const framework = "React";
const database = "MySQL";
const server = "NodeJS";
const company = "ABC Ltd";
const cityName = "Chennai";
const state = "Tamil Nadu";
const currency = "INR";
const university = "University";
const departmentName = "MCA";
const batch = "2024";
const semester = 4;
const sectionName = "A";
const status = "Active";

let name = "Bharath";
console.log(name);


console.log("JavaScript Variables Program Completed");